-- 1. Tabla base de Pokecuentos (Series)
CREATE TABLE IF NOT EXISTS Pokecuento (
  id integer generated by default as identity primary key,
  nombre varchar(50) not null,
  autor varchar(50) not null,
  imagenURL text,
  audioURL text,
  videoURL text
);

INSERT INTO Pokecuento (nombre, autor, imagenurl, audiourl, videourl) 
VALUES (
  'Destino y Deber',
  'Valery Pokecuentos',
  'https://i.ytimg.com/vi/1NF4OsBt6DY/sddefault.jpg',
  'audio',
  'https://www.youtube.com/playlist?list=PLDdPvIW_QZ2Dsi5OZElfxRmP-4O02A1q4'
);

-- 2. Categorías de las Series
CREATE TABLE IF NOT EXISTS categorias_pokeserie (
    id integer generated by default as identity primary key,
    nombre VARCHAR(255) NOT NULL
);

-- Corregido: Se eliminó una categoría duplicada ('Mejor Pareja Sentimental')
INSERT INTO categorias_pokeserie (nombre) 
VALUES 
('Mejor Ambientación musical general (pokeseries)'),
('Mejor Protagonista (pokeseries)'),
('Mejor Villano/Antagonista (pokeseries)'),
('Mejor Co-protagonista (pokeseries)'),
('Mejor Innovación en Historias (pokeseries)'),
('Mejor Arco Argumental (pokeseries)'),
('Mejor Pelea (pokeseries)'),
('Mejor Pareja Sentimental (pokeseries)'),
('Momento Más Emotivo/Impactante (pokeseries)'),
('Mejor Pokewaifu (hembra) (pokeseries)'),
('Mejor Pokehusbando (Machos) (pokeseries)'),
('Mejor Pokeserie');

-- 3. NUEVA TABLA PUENTE: Conecta qué Pokecuento está nominado a qué categoría de serie
CREATE TABLE IF NOT EXISTS nominados_pokeserie (
    categoria_id INT,
    pokecuento_id INT,
    PRIMARY KEY (categoria_id, pokecuento_id),
    FOREIGN KEY (categoria_id) REFERENCES categorias_pokeserie(id) ON DELETE CASCADE,
    FOREIGN KEY (pokecuento_id) REFERENCES Pokecuento(id) ON DELETE CASCADE
);

-- 4. Tabla de Votaciones de Series
CREATE TABLE IF NOT EXISTS votacion_pokeserie (
    id integer generated by default as identity primary key,
    votante_id VARCHAR(255) NOT NULL, -- Identificador del usuario/IP para evitar fraude
    categoria_id INT,
    pokecuento_id INT,
    fecha_votacion timestamp default now(),
    -- Corregido: Apuntaba a 'categorias' en vez de 'categorias_pokeserie'
    FOREIGN KEY (categoria_id) REFERENCES categorias_pokeserie(id), 
    FOREIGN KEY (pokecuento_id) REFERENCES Pokecuento(id),
    -- Restricción para que un votante solo vote una vez por categoría
    UNIQUE (votante_id, categoria_id) 
);


--//////////////////////////////////////////////////////////////////////////////////////////
--                      POKEFILM                                                        ///
--////////////////////////////////////////////////////////////////////////////////////////

-- 1. Tabla base de Pokefilms (Películas)
CREATE TABLE IF NOT EXISTS Pokefilm (
  id integer generated by default as identity primary key,
  nombre varchar(50) not null,
  autor varchar(50) not null,
  imagenURL text,
  audioURL text,
  videoURL text
);

INSERT INTO Pokefilm (nombre, autor, imagenurl, audiourl, videourl) 
VALUES (
  'La Reina y el Ladron',
  'Valery Pokecuentos',
  'https://i.ytimg.com/vi/3b-Wx81fVY4/sddefault.jpg',
  'audio',
  'https://www.youtube.com/watch?v=3b-Wx81fVY4&themeRefresh=1'
);

-- 2. Categorías de las Películas
CREATE TABLE IF NOT EXISTS categorias_pokefilm (
    id integer generated by default as identity primary key,
    nombre VARCHAR(255) NOT NULL
);

-- Corregido: Se eliminó una categoría duplicada y se corrigió el texto de Co-protagonista que decía (pokeseries)
INSERT INTO categorias_pokefilm(nombre) 
VALUES 
('Mejor Ambientación musical general (pokefilms)'),
('Mejor Protagonista (pokefilms)'),
('Mejor Villano/Antagonista (pokefilms)'),
('Mejor Co-protagonista (pokefilms)'),
('Mejor Innovación en Historias (pokefilms)'),
('Mejor Arco Argumental (pokefilms)'),
('Mejor Pelea (pokefilms)'),
('Mejor Pareja Sentimental (pokefilms)'),
('Momento Más Emotivo/Impactante (pokefilms)'),
('Mejor Pokewaifu (hembra) (pokefilms)'),
('Mejor Pokehusbando (Machos) (pokefilms)'),
('Mejor Pokefilm');

-- 3. NUEVA TABLA PUENTE: Conecta qué Pokefilm está nominado a qué categoría de película
CREATE TABLE IF NOT EXISTS nominados_pokefilm (
    categoria_id INT,
    pokefilm_id INT,
    PRIMARY KEY (categoria_id, pokefilm_id),
    FOREIGN KEY (categoria_id) REFERENCES categorias_pokefilm(id) ON DELETE CASCADE,
    FOREIGN KEY (pokefilm_id) REFERENCES Pokefilm(id) ON DELETE CASCADE
);

-- 4. Tabla de Votaciones de Películas
CREATE TABLE IF NOT EXISTS votacion_pokefilm (
    id integer generated by default as identity primary key,
    votante_id VARCHAR(255) NOT NULL, -- Identificador del usuario/IP
    categoria_id INT,
    pokefilm_id INT,
    fecha_votacion timestamp default now(),
    -- Corregido: Apuntaba a 'categorias' y 'pokecuento' erróneamente
    FOREIGN KEY (categoria_id) REFERENCES categorias_pokefilm(id),
    FOREIGN KEY (pokefilm_id) REFERENCES Pokefilm(id),
    -- Restricción única por votante y categoría
    UNIQUE (votante_id, categoria_id)
);


--SQL - Crear taula profiles
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'voter',
  created_at TIMESTAMP DEFAULT now()
);
--SQL - Trigger per crear profile automàticament al registrar-se
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, role)
  VALUES (NEW.id, 'voter');
  RETURN NEW;
END;
-- LANGUAGE plpgsql SECURITY DEFINER;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();
